---
- debug: var=ansible_distribution
- debug: var=ansible_distribution_version
- debug: msg="{{ansible_distribution_version|int}}"

- include_vars: "{{item}}"
  with_first_found:
  - "../vars/{{ansible_distribution}}-{{ansible_distribution_version|int}}.yml"
  - "../vars/{{ansible_distribution}}.yml"
  - "../vars/{{ansible_os_family}}.yml"
  - "../vars/default.yml"
